# generated by datamodel-codegen:
#   filename:  sensor_schema.json
#   timestamp: 2022-11-06T05:25:29+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
