# generated by datamodel-codegen:
#   filename:  sensor_dummy_data.json
#   timestamp: 2022-11-06T09:12:27+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class GPSDatum(BaseModel):
    SnappedLongitude: float
    GPSLongitude: float
    TimeStamp: str
    GPSHeading: int
    GPSAltitude: int
    GPSSpeed: float
    Deviation: float
    FromNodeID: float
    WayID: float
    SnappedLatitude: float
    ToNodeID: float
    HorizontalAccuracy: int
    GPSLatitude: float
    VerticalAccuracy: int


class Model(BaseModel):
    GPSData: List[GPSDatum]
    DataAlgorithmVersion: str
    TripID: int
    StartTime: str
    CompanyID: str
    StartTimeZone: str
    DriverID: str
    EndTime: str
    EndTimeZone: str
